final List<Map<String, String>> listOfpatronAssociations = [
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FAhmedabad%20Andhra%20mahasabha.jpg?alt=media&token=7e9fe6a4-b41d-4068-911c-fa573536352b","Associations":"Ahmedabad Andhra Mahasabha","State":"Gujarat",}

];
final List<Map<String, String>> listOfAssociationMembers = [
  {"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FPondicherry.jpg?alt=media&token=161dfe25-49cf-4d72-a676-4091a6e7e5cf","Association": "Andhra Maha Sabha, Pondichery", "State": "Pondichery"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FTVSM.JPG?alt=media&token=576f707a-51ba-4fad-ac9d-994f2c908226","Association": "Telugu vari Samakhya,Maharashtra .", "State": "Maharashtra"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FAndhra%20culture%20association%2C%20Bhuvneshwar.jpg?alt=media&token=c32598f8-51df-48b0-bc47-a2ae680bbffe","Association": "Andhra cultural Association, Bhuvaneswar", "State": "Orissa"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FIKYATA.jpg?alt=media&token=8cd6e0a6-44cb-4415-afdd-7812449efdb7","Association": "Ikyata, Cuttack", "State": "Orissa"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FPanvel.jpg?alt=media&token=1159c848-96b8-43d7-bef7-189bc2fb9e9b","Association": "Andhra Kala Samiti, New Panvel", "State": "Maharashtra"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FPune.jpg?alt=media&token=88e7560d-627d-45ce-9779-08c4f64a3e79","Association": "Pune Andhra Association", "State": "Maharashtra"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FTitagargh.jpg?alt=media&token=5c422678-66dc-470c-bf8f-2e23d849a450","Association": "Titagarh Andhra Sangham", "State": "Bengal"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FKoshal%20andhra%20culture%20association.png?alt=media&token=748da007-6cd9-4ab3-bf38-f264abd6fd2f","Association": "Koshal Andra Association, Attabira", "State": "Orissa"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FRaghava%20kala%20mandir%2CBellary.jpg?alt=media&token=9dfb2eb0-48c5-47ac-89a5-02caba232567","Association": "Raghava Kala Mandir, Bellary", "State": "Karnataka"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FTelugu%20bhasa%20samkruti%2C%20abhimana%20sangham%2C%20Bhuvneshwar.jpg?alt=media&token=d959c028-6c6c-4309-ae83-f19b7db19eac","Association": "Telugu Bhasha Sanskruti Abhimana Sangham", "State": "Bhuvaneswar"},
{"Logo":"https://firebasestorage.googleapis.com/v0/b/rts-web-dfa05.appspot.com/o/LOGO%2FKolcutta.jpg?alt=media&token=d445a596-4838-4843-9925-55b85bac49ae","Association": "Andhra Association Kolcutta", "State": "Kolcutta"},
];
/*final List<Map<String, String>> listOfAssociationMembers = [
/*{"Association": "Andhra Maha Sabha, Pondichery", "State": "Pondichery"},
  {"Association": "Telugu vari Samakhya,Maharashtra .", "State": "Maharashtra"},
  {"Association": "Andhra cultural Association, Bhuvaneswar", "State": "Orissa"},
  {"Association": "Ikyata, Cuttack", "State": "Orissa"},
  {"Association": "Andhra Kala Samiti, New Panvel", "State": "Maharashtra"},
  {"Association": "Pune Andhra Association", "State": "Maharashtra"},
  {"Association": "Titagarh Andhra Sangham", "State": "Bengal"},
  {"Association": "Coasal Andra Association, Attabira", "State": "Orissa"},
  {"Association": "Raghava Kala Mandir, Bellary", "State": "Karnataka"},
  {"Association": "Telugu Bhasha Sanskruti Abhimana Sangham", "State": "Bhuvaneswar"},
  {"Association": "Andhra Association Kolcutta", "State": "Kolcutta"},
*/
];*/
final List<Map<String, String>> listOfpatronmembers =[
  {"Name":"N.Bose Babu","State":"Gujarat"},
  {"Name":"P,V.P,C.Prasad","State":"Gujarat"},
  {"Name":"Radha Mohan","State":"Maharashtra"},
  {"Name":"K. Venkata Krishna","State":"Tamil Nadu"},
  {"Name":"AVVSSK Krishna Rao","State":"Gujarat"},
  {"Name":"TVN Murthy","State":"Gujarat"},
  {"Name":"D.Prasada Rao","State":"Chennai"},

];
final List<Map<String, String>> listOflifemembers =[
  {"Name":"O.Subramanyam","State":"Maharashtra"},
  {"Name":"R.Sundara Rao","State":"Bengal"},
  {"Name":"V.S.N.Raju","State":"Orissa"},
  {"Name":"R.N.Prasad","State":"Assam"},
  {"Name":"Boyiena Kamaraju","State":"Assam"},
  {"Name":"V.V.Rama Rao","State":"Maharashtra"},
  {"Name":"Raveena Chavan","State":"Maharashtra"},
  {"Name":"Dr.Turlapati Rajeswari","State":"Orissa"},
  {"Name":"N.Satyanarayana Murthy","State":"Orissa"},
  {"Name":"K.S.Krishnappa","State":"Tamil Nadu"},
  {"Name":"K.Narahari Rao","State":"Gujarat"},
  {"Name":"K.V.R.Murthy","State":"Bengal"},
  {"Name":"S.V.Joga rao","State":"Bengal"},
  {"Name":"P.Srirama murthy","State":"Orissa"},
  {"Name":"Pochiraku Suryanarayana Rao","State":"Orissa"},
  {"Name":"Kanuru Gopala Krishna","State":"Orissa"},
  {"Name":"Bujji Siva Prasad Rao","State":"Orissa"},
  {"Name":"V.Bala Rama Raju","State":"Orissa"},
  {"Name":"S.Suryanarayana","State":"Orissa"},
  {"Name":"V.Chandrayya Raju","State":"Orissa"},
  {"Name":"J.Shanmugha Rao","State":"Orissa"},
  {"Name":"L.Seeta","State":"Delhi"},
  {"Name":"P.Satyanarayana","State":"Orissa"},
  {"Name":"Bomma Reddy Koti Reddy","State":"Delhi"},
  {"Name":"V.Balamurali","State":"Bengal"},
  {"Name":"B.Padmini","State":"pumjab"},
  {"Name":"Chalam","State":"Maharashtra"},
  {"Name":"Smt. Vijayalakshmi","State":"Maharashtra"},
  {"Name":"Mallyadri","State":"Orissa"},
  {"Name":"D.Maruti Prasad","State":"Gujarat"},
  {"Name":"J.venkata Ramana","State":"Gujarat"},
  {"Name":"T.harinarayana","State":"Gujarat"},
  {"Name":"Y.Hanuman Prasad","State":"Gujarat"},
  {"Name":"K.Subba Rayudu","State":"Gujarat"},
  {"Name":"R.Raghava Rao","State":"Gujarat"},
  {"Name":"V.Sri GopalaKrishna","State":"Gujarat"},
  {"Name":"S.Srinivasulu","State":"Gujarat"},
  {"Name":"G.Venugopala Rao","State":"Gujarat"},
  {"Name":"T.Vara Prasad","State":"Gujarat"},
  {"Name":"PV Murali Krishna","State":"Gujarat"},
  {"Name":"PVPrasada Rao","State":"Gujarat"},
  {"Name":"DRM Samudraiah","State":"Gujarat"},
  {"Name":"TVS Ram","State":"Gujarat"},
  {"Name":"V. Murali Mohana Krishna","State":"Gujarat"},
  {"Name":"KVN Sarveswara Rao","State":"Gujarat"},
  {"Name":"Dwaraknath Gupta","State":"Gujarat"},
  {"Name":"M.Punna Rao","State":"Gujarat"},
  {"Name":"AVS Sankar","State":"Gujarat"},
  {"Name":"B.Gopal","State":"Gujarat"},
  {"Name":"VS Rao","State":"Gujarat"},
  {"Name":"Y.Subrahmaniam","State":"Gujarat"},
  {"Name":"K.Ravichandra","State":"Gujarat"},
  {"Name":"VGS Sarma","State":"Gujarat"},
  {"Name":"GP Rao","State":"Gujarat"},
  {"Name":"K Srinivas","State":"Gujarat"},
  {"Name":"B.Sreenivasa Rao","State":"Gujarat"},
  {"Name":"G.Nagaraju","State":"Gujarat"},
  {"Name":"L.S.Rao","State":"Gujarat"},
  {"Name":"P.Buchchi Raju","State":"Gujarat"},
  {"Name":"Gottikonda Sreenivasulu","State":"Gujarat"},
  {"Name":"Mallepalli Ramesh Babu","State":"pondichery"},
  {"Name":"K.Chandra Sekhar Raju","State":"pondichery"},
  {"Name":"Prof. Sunkara Ranga Rao","State":"pondichery"},
  {"Name":"Vijaya Ramachandrula","State":"pondichery"},
  {"Name":"Appari Satyanarayana","State":"Maharashtra"},
  {"Name":"Koduru Srinivas","State":"Maharashtra"},
  {"Name":"V.Phani kumar","State":"Maharashtra"},
  {"Name":"Devu Brahmam Achary","State":"Orissa"},
  {"Name":"Medimi Venkata Krishna","State":"Orissa"},
  {"Name":"Nyayapati Lakshmana Rao","State":"Orissa"},
  {"Name":"M venkateswara Rao","State":"Orissa"},
  {"Name":"V.srinivas","State":"Orissa"},
  {"Name":"Vemuri subhash Naidu","State":"Orissa"},
  {"Name":"G Kailash","State":"Orissa"},
  {"Name":"Kolli Sreenivasa Rao","State":"Orissa"},
  {"Name":"kumar","State":"Orissa"},
  {"Name":"J Mohan Rao","State":"Orissa"},
  {"Name":"K Siva Prasad Subuddhi","State":"Orissa"},
  {"Name":"P Chittibabu","State":"Orissa"},
  {"Name":"V Visweswara Rao","State":"Orissa"},
  {"Name":"M.Sampat Kumar","State":"Tamil Nadu"},
  {"Name":"GVSR Krishna Murty","State":"Tamil Nadu"},
  {"Name":"P.T.Srinath","State":"Bengal"},
  {"Name":"A.Srinivasarao","State":"Bengal"},
  {"Name":"M.Sivalingam","State":"Bengal"},
  {"Name":"P.Sannibabu","State":"Bengal"},
  {"Name":"NSK Rao","State":"Bengal"},
  {"Name":"E Veeraraju","State":"Bengal"},
  {"Name":"Venugopala Rao, President,, AA,IIT","State":"Bengal"},
  {"Name":"Vedula Venkatarao","State":"Bengal"},
  {"Name":"Vedula Sai Srinivas","State":"Bengal"},
  {"Name":"DM Srivivas","State":"Bengal"},
  {"Name":"Suri Pattabhi","State":"Bengal"},
  {"Name":"DB Yerrayya","State":"Bengal"},
  {"Name":"KRVS Meher","State":"Bengal"},
  {"Name":"Maddu Samba Murthy","State":"Bengal"},
  {"Name":"Pramod Kumar","State":"Bengal"},
  {"Name":"Dhavala Visveswararao","State":"Bengal"},
  {"Name":"Rallapalli Padma Prasad","State":"Bengal"},
  {"Name":"Katyayani","State":"Bengal"},
  {"Name":"K.V.Ramana rao","State":"Bengal"},
  {"Name":"Devatha Subramaniyam","State":"Bengal"},
  {"Name":"Kolla Lokeswara Rao","State":"Bengal"},
  {"Name":"Ganti Pradeep","State":"Bengal"},
  {"Name":"Bantupalli Sundara Rao","State":"Bengal"},
  {"Name":"VVL Srinivasa Murty","State":"Delhi"},
  {"Name":"B.Chanti Prasada Rao","State":"Bengal"},
  {"Name":"N/Nagabhushana Rao","State":"Orissa"},
  {"Name":"B.Krishna Rao","State":"Kharagur"},
  {"Name":"P.Bhasakara Rao","State":"Kharagur"},
  {"Name":"PV Appala Das","State":"Kharagur"},
  {"Name":"V Nageswara Rao","State":"Kharagur"},
  {"Name":"Chenna Reddy","State":"Kharagur"},
  {"Name":"M Yagna narayana","State":"kerala"},
  {"Name":"Sappidi","State":"Orissa"},
  {"Name":"Asipu Bairagi","State":"Bengal"},
  {"Name":"P.Bhaskara Reddy","State":"karnataka"},
  {"Name":"Hanumantha Rao","State":"karnataka"},
  {"Name":"M. Ramaswami Reddy","State":"Tamil Nadu"},
  {"Name":"P.Krishna Murty","State":"Orissa"},
  {"Name":"Otti Bhuteswar","State":"Bengal"},
  {"Name":"Korada Nageswar Rao","State":"Bengal"},
  {"Name":"Battala Rama Rao","State":"Bengal"},
  {"Name":"Boda Tarakesu","State":"Bengal"},
  {"Name":"Pilli Mohan Rao","State":"Bengal"},
  {"Name":"Telukula Krishna Shahu","State":"Bengal"},
  {"Name":"Balla Prakash Rao","State":"Bengal"},
  {"Name":"Ankam Syamala","State":"Bengal"},
  {"Name":"Vaka Bharathi","State":"Bengal"},
  {"Name":"Allaka Madhubabu","State":"Bengal"},
  {"Name":"KSR Krishna","State":"Maharashtra"},
  {"Name":"B.SUBBA RAO","State":"Bengal"},
  {"Name":"V. SHIVA SATYANANDAM","State":"Bengal"},
  {"Name":"M. PATTABHIRAM","State":"Bengal"},
  {"Name":"G. ANANDA RAO","State":"Orissa"},
  {"Name":"D. MURALIKRISHNA","State":"Orissa"},
  {"Name":"B. BULLIAH CHOWDARY","State":"Orissa"},
  {"Name":"V. VEERABHADRA RAO","State":"Orissa"},
  {"Name":"P. JAYARAMULU","State":"Orissa"},
  {"Name":"DR. RSN MURTY","State":"Orissa"},
  {"Name":"K S R RAMESH","State":"Orissa"},
  {"Name":"P. VENUGOPAL","State":"Orissa"},
  {"Name":"RUDRA MURTHY","State":"chhattisgarh"},
  {"Name":"ANANDARAO PATNAIK","State":"Orissa"},
  {"Name":"BABURAO MAHANTY","State":"Orissa"},
  {"Name":"L. KALAVATHI","State":"Orissa"},
  {"Name":"S. VISWANADHA RAO","State":"chhattisgarh"},
  {"Name":"A. PADMAVATHI","State":"Delhi"},
  {"Name":"M. KUSUMA","State":"Delhi"},
  {"Name":"Y. PARVATHI REDDY","State":"Delhi"},
  {"Name":"VIJYAKUMAR","State":"Tamil Nadu"},
  {"Name":"A.M. SUBRAHMANYAM","State":"Tamil Nadu"},
  {"Name":"MADHUKUMAR REDDY","State":"Tamil Nadu"},
  {"Name":"M. CHANDRASEKHAR","State":"Tamil Nadu"},
  {"Name":"M.S. LAKSHMA REDDY","State":"Tamil Nadu"},
  {"Name":"D.Koteeswara Rao","State":"Karnataka"},
  {"Name":"Chennappa","State":"Karnataka"},
  {"Name":"Renuka","State":"Maharashtra"},
  {"Name":"K.KEDARINATH","State":"Orissa"},
  {"Name":"SETUPATI ADINARAYANA","State":"Orissa"},
  {"Name":"G SEKHAR REDDY","State":"karnataka"},
  {"Name":"G MUNI REDDY","State":"Tamil Nadu"},
  {"Name":"NANDULA RAMAKRISHNA","State":"Maharashtra"},
  {"Name":"Syamala Devi","State":"Karnataka"},
  {"Name":"Tirumala Kumar","State":"Tamil Nadu"},
  {"Name":"R.Sankaran","State":"Tamil Nadu"},
  {"Name":"PH Rao","State":"Gujarat"},
  {"Name":"Jonnalagadda Srinath","State":"kerala"},
  {"Name":"Srinivasa Murty Mellacheruvu","State":"Jharkhand"},
  {"Name":"Erramilli Sri Mata","State":"Gujarat"},
  {"Name":"Lellapalli Sridevi Ramesh","State":"Tamil Nadu"},
  {"Name":"RVSN Murty","State":"West Bengal"},
  {"Name":"Chellapilla Vardhan Kumar","State":"West Bengal"},
  {"Name":"Janatala Jyotsna","State":"Orissa"},
  {"Name":"B RajeshWara Raju","State":"West Bengal"},
  {"Name":"Ivaturi Dhana Lakshmi","State":"West Bengal"},
  {"Name":"KV Rao","State":"Dadra Nagar Haveli"},
  {"Name":"Venkateswara Rao","State":" Karnataka"},
  {"Name":"Prayaga Aruna","State":"West Bengal"},
  {"Name":"Sudhakara Reddy","State":"Uttar Pradesh"},
  {"Name":"KV Rajeswara Rao","State":"Rajasthan"},
  {"Name":"K.Srinivas","State":"Assam"},
  {"Name":"NN Murty","State":"Maharashtra"},
  {"Name":"Sangineni Ravindra","State":"Maharashtra"},
  {"Name":"C Murali Krishna","State":"Karnataka"},
  {"Name":"N.Krishna Reddy","State":"Tamil Nadu"},
  {"Name":"R.Gajendra Murty","State":"Tamil Nadu"},
  {"Name":"K.Tyagaraj","State":"Tamil Nadu"},
  {"Name":"Sonti Sarada","State":"Orissa"},
  {"Name":"SN Srinivas","State":"Orissa"},
  {"Name":"AV Sitaramaiah","State":"Tamil Nadu"},
  {"Name":"P.Ramalingeswara Rao","State":"Orissa"},
  {"Name":"M Ramachandrappa","State":"Tamil Nadu"},
  {"Name":"A purnalata","State":"West Bengal"},
  {"Name":"P.Srinivasa Rao","State":"chhattisgarh"},
  {"Name":"G Krishnappa","State":"Tamil Nadu"},
  {"Name":"Deverakonda Vaidya Narayana Rao","State":"Orissa"},
  {"Name":"A Malleswara Rao","State":"West Bengal"},
  {"Name":"K Suryanarayana Murty","State":"Tamil Nadu"},
  {"Name":"Dr Sivam Arun Kumar","State":"chhattisgarh"},
  {"Name":"B Ramakrishna","State":"Orissa"},
  {"Name":"Reddy Veeraswamy","State":"chhattisgarh"},
  {"Name":"C.Jagadeeswari","State":"Karnataka"},
  {"Name":"Malyadri","State":"Karnataka"},
  {"Name":"M.Muniraju","State":"Karnataka"},
  {"Name":"DNV Rama Sarma","State":"Karnataka"},
  {"Name":"Darla Venkateswarlu","State":"Karnataka"},
  {"Name":"B Prabhakara Rao","State":"West Bengal"},
  {"Name":"A. Chandra Sekhar","State":"Tamil Nadu"},
  {"Name":"KS Jeeva Ratnam","State":"Karnataka"},

 ];
final List<Map<String, String>> listOfassociatemembers =[
  {"Name":"S.A.Nazeer","State":"Telangana"},
  {"Name":"Dantu Subba Rao","State":"Telangana"},
  {"Name":"M.Anantham","State":"Telangana"},
  {"Name":"Smt. V.Kanaka Durga","State":"Telangana"},
  {"Name":"KBS Sarma","State":"Telangana"},
  {"Name":"Dr. GV Purnachand","State":"Andhra Pradesh"},
  {"Name":"Smt. Prabhala Janaki","State":"Telangana"},
  {"Name":"Dr.Kolli Mohana Rao","State":"Andhra Pradesh"},
  {"Name":"GLN Murty","State":"Telangana"},
  {"Name":"Bandi Lakshmi Narayana","State":"Andhra Pradesh"},
  {"Name":"Ananda Mohan Voruganti","State":"Telangana"},
  {"Name":"Chaganti Uma","State":"Andhra Pradesh"},
  {"Name":"T Girija","State":"Telangana"},
  ];