final List<Map<String, String>> listOfpatronAssociations = [
{"Logo":"https://lh3.googleusercontent.com/WxOsmgPWg-HkmD7lZCEs1khW6czeam9vBg3PKMsvUAk5Y93OcHaDeZpvl-vt1rKQusOMzGapG67NI36eqKEyzKU0dp_yEnS5hiNLexuqlL_XBgYp2ZtaTuUdx4VEvb-Ag1mLnew45OoqUkJC47GcU3l-FEE0yoUyUnCRsRA8mlcyu-7tyBF9eTRqwpPv8KVHED8OPJoLuGwaDTFrAxKMoOD2yib4Z-pN2QdygUD06gyGAx4gcy2INqlq114wdcu0mCECOnobMuczEV425UiXjcQbxW355p0K4ml1jHAPRNkVG7pwFwbE6yj1Kgg6G12PLAExPswOJNc5CAcq4Je4v_SQyCimGqSLgcXQjxytu5OhzXzh6_2enU18FDwCofxjv1-ymsjQcKXNMkP39ncy8SzyV_gj9zzZTyYy5Uc67NJ70rTmOFk-JnJP3hLNL37Payx42CFr8P2HoheuerAMSNfwTUQG7aDllW9zMR0TKsIS5nQd2f6guTiYIOETjIsKM-y58m6G2qSqidQEUdju6GchI7_KHOfRzmH7itxAfpzW3lqEj5MnuUwRfwfrGtgcUSYubV-TZdrfEhQBIjGJLZZYMRc4TIxvXKE472_g87Nt5fHmR0Djxi4AIDQ40NZU6RSMEpKZvQgemdUj_hzinbmquKG8GX4aqTAy6vkePG0I0e4IiJdJ7loY4HU=w97-h96-no?authuser=4","Associations":"Ahmedabad Andhra Mahasabha","State":"Gujarat",}

];
final List<Map<String, String>> listOfAssociationMembers = [
{"Logo":"https://lh3.googleusercontent.com/-QUCTPpSCc796qBAJUfDHmDK5HIb6r3Lr64JMZyzJGlN_WYxQAqsgZdKAaBzy5SDKBm4Ao4Qza0jKOjjCSf9KeJM9Si51bETiHSgD9QytNtQBHteE7zeBDcSX1v8t948cgRi_2yQgbWVMm9lWWXMpI6yVZA7LTuEjGYYafnvLWnofVzKlYtoz2ICUx-rgPeWDOgszqfXgkYLpO6iLKqmhRESumE2kAXxSDYk0Ze8ihMMUooBs9bH9LWRR8xUtnYc8l0jZi57_aUYBwRqzFJnu1-Hwr3srGPC1rjhYTRUSTOJdPeTltaW0F5Zmer7zLF4mTt8gUOtIB_jZfOQNR9RRB0foK18hOKXkw4JwONC4lOJe0A-xJ6Fn0nPmz6vJpBMCIJ2jUcNJUdxBZnc6WkNhqJiaj7VuGwji9u5MT4tQFzsDZWAP27rmNJGGhu-0XyBDTwpSAkf1sYwPQGZ62qCYFVQ2IntL3RUem1yJV2v5WD4JPzrnEK5u9zW7OwEWJ8VhCmzCwchk4XbfCw9sWnHJhhr6LUP15oAsFRlhk6Pk6dE-vpiWsXl40zvydzF1M8aFnZ_di0fD8OIe-LLdy3JiKrcFEDO1zo5E1P6gK9zpz6lzVAOne61KcwW9qTqcpG1GW845kiaQVr4NDnZYI7pctatQKirv4cpKuc0zOPyoTkac5e8_iTP7Vr4aec=w202-h56-no?authuser=4","Association": "Telugu vari Samakhya,Maharashtra .", "State": "Maharashtra"},
{"Logo":"https://lh3.googleusercontent.com/SS5IXHMgoSL2SjKRpTlL452OyOc8eoWR0VgA55c5gGC3ZubMLzzqvPd9ky-vu8bSwcT3cGB04TQNpZqZDw5bsQ5TRt68lw-PhkKOhFY3754j3ZZ-84HhzYD8_dWtnV_NwdTwC-Lw61nnshMqoZGgsW4xfzDNU1SV9kri2XzeN1UA2D2TJ9brLwA3FuYeK87hhQoCVUAx1UAEnNG1wLvTzomufkmz13kcUvDr2TIlv1gfZd4x4A6slwu2hyuvYe9vxrYk1exZlzMDXE5IfGvqmWNZ_X9RpYXPvpYsfWkYTOrbAjvmegI3mX3AkAQBWNvjHCBhWbBNMd_rG3IUOCMe5gSAXs2OFdUPvqIJ8WkUJ4-jcsuSyyAtnJqOEB3iRZ2vSvmMx7U06SVQoR5SQoblMMh2poTNfI86Jus3paB9rGywLgdnV_BrmwLTvkFwmtvrPhNFN_W55tjK5UWNOn2w_PznaimIqBTKoBE0e3lvCV3mmdvxuP27jzZGbeCl3vCkZvPqljct1KEYHUk5d889Iibon3j9ouQN3JkeLT7jJg-MBUmI-vrFimxQtFYwRW3cGil7nma5WTlqM9Hci3DkBijbDHRRiagpFGTwg2838bnGbijGxNdfVY1E3GnuFy-7A6GlpJ2uTY5wYLeS_sj4SdJjciIK27jzvKzikIMADx06EihqpwLQmiEHF1c=w310-h494-no?authuser=4","Association": "Andhra cultural Association, Bhuvaneswar", "State": "Orissa"},
{"Logo":"https://lh3.googleusercontent.com/hqs3YOXzwhmvTJmr7EuCMuI_l78mloW0rRyHHOWBiMcyqWM-MbciE9KqR_dyUmVHTAsaJ05d7tey_ch_qlxidndDFoPmiPblX00RVu-D_zneu6ESRQraF4gHicDln3QXrkIzqdm0YGd3H_qsT-mZuUUCpgsLDbZ9Z0s9uriUjh8_OoD_FYFzhYbz_SEPO-nBFMNlAX50DmKWp7ackZZjLP8gMc08Dj-Huy0kEvWmZiUSqRFjJ1XDWn2rsU5Uzqjr_XcsJv5rd6H8NMbi7z2PlXkEZ8UluOUCdHDgef5c-gYXDNj8zAv32HvlqHf2Hbg7ZFQk70pZY8wk5aL5z8yDm_wMr9Xpg4YsmEr5Xu-78KCxr4M9NOsrobOMTqIM0HBtwQBoTI46ScNoFBYYzeuUvz_77mKoK7oHHDTd3w4i2Zi-npOItpK7yR64HRhKsAv0Xr4nVWTonyUu0zVO6Aamm18CSJ2MB2ClKdLD5WUf79WS1S-6orgKekfLFxGpoIEylOar1clFjXpquh-ji4hwtcXSOKastLgDfhAXUQsehTZlwREMCn5xD4N9XPDEz_R53LzdQ-YQqgxYO-WcIpY6JX8vjwJk3SlfOlaJK7Pdl9yEix4t-b9h2sUyLGK1y6DzPc1m4PydfcWKuVvkPD1ABuN2KO4mPLGFDb-XLXUkswPHITT7DYlU_OhBbAk=w770-h937-no?authuser=4","Association": "Ikyata, Cuttack", "State": "Orissa"},
{"Logo":"https://lh3.googleusercontent.com/UbGYMQVcKwc5BmppeKvqH6fx_s-wFtk01ConUJUVRP2A6kehKwarV16LGHawG0B1poHfcuOm3iVWOAgJsjgtOKkqY-CJF_6w2k-Y1qSNIkuZh-7XQM0hUEDa_xBIRgUWtQrM3oq_5NylDUF3s0creOQTYZ3VZ4zdAXv6sB09jBWa9AXqNVscDHnXLUYbSYIFYfdo2mwMx3oKtVQR6cWkhw_czmCkSyPv54vyspqH5EiR8BYyLPlu_2L6yJRBahXVas-rr_sOOe93xKbeOzt-uGwIE6LShSg8xJvO_kqlCwx_tAga9jql4J7ymjFeO3uwycdFcUFV-l2wPxi_EzuOn-K5Lfq6e0tHU0Elk7FUx3DpEuSeZA2YxIi6CJCfr13kJv51rx2REFRknnCVB354AAV5VkIof750My0s1C0e_hGkSBFAcjLhoK06v741E0Cr8TxWO2mlhEinhC28C5FKscAoa7RAU1mN5xBa-COju-gQADr7Iw-HySvBqBDK_nuHT_Kbz-kxt3lqFcCadbG_T5s6yxwCwvHJhTMfADDrS8wSsYKRrxzg54MtFPMDpfCTqm4cTFU-Tk6Kvs54J0-NbvNgAYb14HX5_9n1UcaDd_qal-2oA7YdpOgU3HD4ul4GPNwxZ1iTxyaTgDgo97IRefp31nw0hIdwhjv-0sCzUz_izaU-FZ2EOV3NhPg=w1125-h791-no?authuser=4","Association": "Andhra Kala Samiti, New Panvel", "State": "Maharashtra"},
{"Logo":"https://lh3.googleusercontent.com/3g5Vs-TNLeqGBLULkjpYudqFYSpRwBYMyLxcWmyMcE20OrLQ0gsWTdoMqDkYrq4kHftlHvugvaYBI4rO1pGpqKLEEHQbHa-qwOOS7pGaL34of_L94cw8UEeFE6_QrL3MEqPjPAdvn9U5CQbcfmd4iw0qkzDbGNFPxuBg3Di5CceqrM5_V3kiAY0JUoonfNcUTp8zFSY7yM6Qef9jUz4F18Wdc7sVZekQKewh3wTWfnzVbFAVlbe23ZmQJhHmaTLMQ4lBkbuqJEEgq9_o1yFmQc-ykIML9RIqyXxFHc4pdZYEszPnNyxMLygVSKNbEibDqRhBhbTzvljcvUTdlDdwEykOQAMkWNPJ7i-sR-RIp2AUD9oaX6OchJ1q0YVt-6WEAL4LPWoJsKd8wthKEWUMbU3f_ghOaILwgzGAshERnaLRjyFGIIgd9NKO3DKiuneuBcLyBckj_AvKe3R_H9jkcM7X72icp2UFmtA7PRuTt2YVlC7sWeBiBkkEUoRfiS0QgXLz7JxcJYlVV8vGPjyW0rjgpZ8THKyLFJ-TZ__UHVmMUOr-mKyCFD9neLCOaeHqWVH1XGhQecFsba_r3Qkk9Gvb0GQGjUurG3PKeIZ7_TcJooPdNfqS3i7MF-nfLCljqjVGfXfwcUCvNhjkyur_HUOtpHMbwTrKQGisK8W_eSYO-o7-yrm_IfLR5YU=w885-h937-no?authuser=4","Association": "Pune Andhra Association", "State": "Maharashtra"},
{"Logo":"https://lh3.googleusercontent.com/Q8QGNTbI9jgVnUtNGVDjsqGyzB1-xwm14fRNVKp0O4lgi9Y9JKy_DQA48QB0vODHguS9s8a6hcBXf1yKEV4mX0fq1BNsBxGaHXPLm6EG-HtY39J3Yh6wlG8HZm3oAhT42othAtOokBJDOE8nDG-xJOSOkzvvuJqrJpomC40RJL42LVQPOeMW2tK-I0vgDj85dTptadUTiVmu_N6hxRjn9Zpm9z084rPGuAnJpeMJ1R0NYOtVJQ0dXDq0ba76TnFMbJqCwi6mQcq976ayBWQP7dK40huj423bO7Gfh6BD7KsiWZm-CYpiSjQ2z8ToxA0tojMgK1YfhTCJCQebHRlku2kf75vxyasBasA0PnKRw6Qmfifw-fjqqVuB2_fTVwK--p65Uv-J0HkhEush3ZiIFsBmzIpZrQlttZvuz9_l9j8dzSy3USzb9DlS7jqVfpRYC7dTSEBEEQ9XJVc3TOdwmdBUvwbCqSSSh-ROST31Ba8lyEFcBFq4pzRO5ZV0x4hFa1NDcLlufSdbbWSJ3bdqSgTsBTpdyzEIsNzgD4ANrcWY2jB52vHP4Pvg29uybVI0gE7ou8B_IMkZIfZbcj6bH3x1uvAODVNVJhGk_tYgo3wyRq6gNwnzOkBvOa0GBlMvckY1oFeqJ3LcAhVyNqAW1XwjspJMUgS8oTHuuNVXOcqOVOnANFkT8quy-bk=w754-h504-no?authuser=4","Association": "Titagarh Andhra Sangham", "State": "Bengal"},
{"Logo":"https://lh3.googleusercontent.com/X63A7Hk2NE5K4Wsf3-nM5cR7CHMXcuuPqY2nz9jczrQAXgIzMXcsfQ6ppsd6xwANgs2nhQcpiEsnBGtNltUFVcUD70wvHrDwnuqMQcAiLuEogLFTxXPfkfI0IoUbkIZBNpR4DjWe65GylgbnR8-wt1QXNZdAAQLWkLW5gjq2vbbAQtKa2-78zZ0tLIjvaISWqgEceDPhJ13QMDuXrhBc-dLfGW4R10Rt7lERGqvAmW87lIdg2uIwl4fh5AOgqToOXFpl6iXcxo2i8ncxHFqnhEsK1XYf4-3kwc_lfaIctKDFJld5ApLplQduiq-Qn4_PJz-vug9Yx6KdkEnyQk0bBM3qmUv2bPJguKCufNS9f1Iw9046WRa0UEV9FB1itxRh8Ry9yPxKpMgK5jaGVH-PvKULpT_efK9nsYlAOKGFAgq23zuHmM8v0XFrxhnfZoQD7it0YW7KoscTEj1FXwy6o982NUuSB9ME3dujqSmHpiJnCslYoDRNnWgKhtJdTZ5E0VCqpNtfoNbzS6GQzAzafgtYuSahlunxGHFjxeZTX-W75As6ksvVpI3o6v7qRoHpXYn-euCNsOl-VKA1bZg491RNhK7IF9ldbmOC8iNXocieAM9gTz7pjINTRMZ9qkDmheZMiYbP9k1M7TdWIs0NmV3mSb2f6-iQU72Em5hFjAz5i3R9-u4RzP8n-BA=s937-no?authuser=4","Association": "Koshal Andra Association, Attabira", "State": "Orissa"},
{"Logo":"https://lh3.googleusercontent.com/NGf74uxQaoE3uE46uYZ3z4AhHjSNejQNEAViYO14endF_9_OsL2JRW_3OrGkEYlpgv0ec1Vl_-wtjjffgVozj4HkjRAE_XECNuRTLvSa3-mnJgfI2CYpd3V7VJsegK961TEaGb4E7b_SoZMnGmS4l2dUuxtbdxD4w5vkxbVERYN7EGJbyo0TpYTeLC7YpAuzjOox2F1ZGFu29uL_yWg_y7hsyUitCpFq4NRPmAUU55zt9zTfyu48vb33lrrsKHLnoHNbTEp1D8nfTgXyxwbrXw4SOjoti8aLtIpyrc0WZ5iwpP5WbHAlFBuq_7p8sc7xD-lFPHI334HUakA8WiC90-UaLQe7NBizK06AxFIq-O0_Lz9QwyxmVKgRxYsqQ_JSwwWTWPdKdHKwezg0LJw-EIqS6cK1VJC0ZsllzAJmfwDZLFRmbmWsD4b-9EW3uMiAirJB24nxyZlZT9GT7IxfTf9z0Ol-OQe4KRImIObRylRKbR0nReeBiYIRWUT9aDgvSZ77ibL3z9aC0px8ifqx1laB6yhHXbzp-5fV4w6OaYsCvlBtXSX6_AArFjlQ3_a9GCPOlmr2aITSd_GoVn-498FMNPmJAafwwWq1xaPeMxjsuT04dHR7nbPCeFFnhvIL6fl5sPNGOf1rraWOFuC-CG-3QMSTG-VoExGdkhiQPq4HKfG76tb1qLuM4nk=w649-h866-no?authuser=4","Association": "Raghava Kala Mandir, Bellary", "State": "Karnataka"},
{"Logo":"https://lh3.googleusercontent.com/83Gfw3ww6zez-9e13OoQv4gz-SvsQ8ctdhH8Y9mI5-V_mlYBejDqhtmXnSvX0-pB1eSh8T94Vj4AUMmRmWEzaQSEoVadsu7eYodwcXCvd0xTI9LRJDpUmHAFmol1RmVSIhVOjYneGHrlkCBEz4uFnshznHiwsb2-CWhOT8Wu5u9Lk3TDaSdViCkyU0nLdNFC6V1X30sYvIQsZtp-nAC-32yW6tbAHwbKAXdnFcUMLTJImiPayXyu0SW3z8pAElzJeBUyR76VvEAe-rcSyHdTfV6H_t4v0Tfprm1XzB_hCYCs0ufi_XqeH1On4c0WOLAGsx9BAq2ZW4MlWFRHvifChGPSgDfqvo8xroNnp4YyRPmF5ijJFRECol-ZMEo1z0wV1TEIGubzz9Gg4QwT8nbRToSCuTQD1m_jt0AzXhJmckSz_GFZTfKdenR4qjprM2sc1MLjdRw5S74qjXhgkq4E3KR9c6F4D_eH89JH_dlALbDceg5M6GktJNW5inQ0-FqDmJZ5E36LACDciRPoFyA6sqqdAOnb5a5XOTEzNFjSDQu26UueTGymJRoBB2RW0hMx0yl2WUuH6uMizWVmc_VfO0TqRBMyvCwiCaf9yW1Y1yG-JjLW_74hkqst_Cy8Kq981-dVRDwzCWTocF5Eeh1ZuIIVJiBZPrcGljPkLCtKp2o5DhvB4ZE9NJtnVIA=w134-h138-no?authuser=4","Association": "Telugu Bhasha Sanskruti Abhimana Sangham", "State": "Bhuvaneswar"},
{"Logo":"https://lh3.googleusercontent.com/51ajCjx_xOIVZa2ktPTzGmJ9FyUvlt4qVQwvL8N7b1B7Wukqi3IQ-ZwF9ssHqlosm-IW0uy0tEEg5AcTNRnaNlZduhOcOb3d4OmeF4inPyWwIcCjQpGTaTw6PsW7j5WcJSACIf0RxDV9H07V3U0ATaRMi6I6kzCo3vWbFqsh1NZAPn_Px3lxRDu49dF3lJ-PehLW0itn0FAc_CIjhAGv8uvcZLheFSi_tladF8Bu335g2ruirGSBeUmnYzov1m9qOEm0FQzptPWJbVp94mcLh7SrmgLKZzYOgwYJL3vuuMG1hzwRyf62qMdsnhmD5Tpp4Li5kAeXCaJLEHBf3DD2NV2ZCAtp5s_foC3U5rQ9j4q2OrUTqNTpYNtKULv-QlQErU8SkFFxLJFhGz9xcZ75nmXqgBBpApu-64t2jzSAl3nHr3ZvBumJPtiAOWP0vWkCEVR8yzsU5nDUXS7PrSD-2pgJFgoWs_OdZcqp9dGjicB8Rd_6VtTXX3LQaP9l3MryPTqTDHn8bu1r95dEiFy9p7ohnVHKsnppAjhZ3o6wdEROt47KsuzVcE4OSEEfix9BX1YRCVirFeiDBGZJc29J2aBs1SLz54dvQgLpsY567OhdtIr-s5ENKS_DJQrDzSsHUyfnSH8VlbezHBTqiY2Zd0DMI7lW8hSagxnOOsQDdM99wWPnVWd_93O78_0=w375-h376-no?authuser=4","Association": "Andhra Association Kolcutta", "State": "Kolcutta"},
];
/*final List<Map<String, String>> listOfAssociationMembers = [
/*{"Association": "Andhra Maha Sabha, Pondichery", "State": "Pondichery"},
  {"Association": "Telugu vari Samakhya,Maharashtra .", "State": "Maharashtra"},
  {"Association": "Andhra cultural Association, Bhuvaneswar", "State": "Orissa"},
  {"Association": "Ikyata, Cuttack", "State": "Orissa"},
  {"Association": "Andhra Kala Samiti, New Panvel", "State": "Maharashtra"},
  {"Association": "Pune Andhra Association", "State": "Maharashtra"},
  {"Association": "Titagarh Andhra Sangham", "State": "Bengal"},
  {"Association": "Coasal Andra Association, Attabira", "State": "Orissa"},
  {"Association": "Raghava Kala Mandir, Bellary", "State": "Karnataka"},
  {"Association": "Telugu Bhasha Sanskruti Abhimana Sangham", "State": "Bhuvaneswar"},
  {"Association": "Andhra Association Kolcutta", "State": "Kolcutta"},
*/
];*/
final List<Map<String, String>> listOfpatronmembers =[
  {"Name":"N.Bose Babu","State":"Gujarat"},
  {"Name":"P,V.P,C.Prasad","State":"Gujarat"},
  {"Name":"Radha Mohan","State":"Maharashtra"},
  {"Name":"K. Venkata Krishna","State":"Tamil Nadu"},
  {"Name":"AVVSSK Krishna Rao","State":"Gujarat"},
  {"Name":"TVN Murthy","State":"Gujarat"},
  {"Name":"D.Prasada Rao","State":"Chennai"},

];
final List<Map<String, String>> listOflifemembers =[
  {"Name":"O.Subramanyam","State":"Maharashtra"},
  {"Name":"R.Sundara Rao","State":"Bengal"},
  {"Name":"V.S.N.Raju","State":"Orissa"},
  {"Name":"R.N.Prasad","State":"Assam"},
  {"Name":"Boyiena Kamaraju","State":"Assam"},
  {"Name":"V.V.Rama Rao","State":"Maharashtra"},
  {"Name":"Raveena Chavan","State":"Maharashtra"},
  {"Name":"Dr.Turlapati Rajeswari","State":"Orissa"},
  {"Name":"N.Satyanarayana Murthy","State":"Orissa"},
  {"Name":"K.S.Krishnappa","State":"Tamil Nadu"},
  {"Name":"K.Narahari Rao","State":"Gujarat"},
  {"Name":"K.V.R.Murthy","State":"Bengal"},
  {"Name":"S.V.Joga rao","State":"Bengal"},
  {"Name":"P.Srirama murthy","State":"Orissa"},
  {"Name":"Pochiraku Suryanarayana Rao","State":"Orissa"},
  {"Name":"Kanuru Gopala Krishna","State":"Orissa"},
  {"Name":"Bujji Siva Prasad Rao","State":"Orissa"},
  {"Name":"V.Bala Rama Raju","State":"Orissa"},
  {"Name":"S.Suryanarayana","State":"Orissa"},
  {"Name":"V.Chandrayya Raju","State":"Orissa"},
  {"Name":"J.Shanmugha Rao","State":"Orissa"},
  {"Name":"L.Seeta","State":"Delhi"},
  {"Name":"P.Satyanarayana","State":"Orissa"},
  {"Name":"Bomma Reddy Koti Reddy","State":"Delhi"},
  {"Name":"V.Balamurali","State":"Bengal"},
  {"Name":"B.Padmini","State":"pumjab"},
  {"Name":"Chalam","State":"Maharashtra"},
  {"Name":"Smt. Vijayalakshmi","State":"Maharashtra"},
  {"Name":"Mallyadri","State":"Orissa"},
  {"Name":"D.Maruti Prasad","State":"Gujarat"},
  {"Name":"J.venkata Ramana","State":"Gujarat"},
  {"Name":"T.harinarayana","State":"Gujarat"},
  {"Name":"Y.Hanuman Prasad","State":"Gujarat"},
  {"Name":"K.Subba Rayudu","State":"Gujarat"},
  {"Name":"R.Raghava Rao","State":"Gujarat"},
  {"Name":"V.Sri GopalaKrishna","State":"Gujarat"},
  {"Name":"S.Srinivasulu","State":"Gujarat"},
  {"Name":"G.Venugopala Rao","State":"Gujarat"},
  {"Name":"T.Vara Prasad","State":"Gujarat"},
  {"Name":"PV Murali Krishna","State":"Gujarat"},
  {"Name":"PVPrasada Rao","State":"Gujarat"},
  {"Name":"DRM Samudraiah","State":"Gujarat"},
  {"Name":"TVS Ram","State":"Gujarat"},
  {"Name":"V. Murali Mohana Krishna","State":"Gujarat"},
  {"Name":"KVN Sarveswara Rao","State":"Gujarat"},
  {"Name":"Dwaraknath Gupta","State":"Gujarat"},
  {"Name":"M.Punna Rao","State":"Gujarat"},
  {"Name":"AVS Sankar","State":"Gujarat"},
  {"Name":"B.Gopal","State":"Gujarat"},
  {"Name":"VS Rao","State":"Gujarat"},
  {"Name":"Y.Subrahmaniam","State":"Gujarat"},
  {"Name":"K.Ravichandra","State":"Gujarat"},
  {"Name":"VGS Sarma","State":"Gujarat"},
  {"Name":"GP Rao","State":"Gujarat"},
  {"Name":"K Srinivas","State":"Gujarat"},
  {"Name":"B.Sreenivasa Rao","State":"Gujarat"},
  {"Name":"G.Nagaraju","State":"Gujarat"},
  {"Name":"L.S.Rao","State":"Gujarat"},
  {"Name":"P.Buchchi Raju","State":"Gujarat"},
  {"Name":"Gottikonda Sreenivasulu","State":"Gujarat"},
  {"Name":"Mallepalli Ramesh Babu","State":"pondichery"},
  {"Name":"K.Chandra Sekhar Raju","State":"pondichery"},
  {"Name":"Prof. Sunkara Ranga Rao","State":"pondichery"},
  {"Name":"Vijaya Ramachandrula","State":"pondichery"},
  {"Name":"Appari Satyanarayana","State":"Maharashtra"},
  {"Name":"Koduru Srinivas","State":"Maharashtra"},
  {"Name":"V.Phani kumar","State":"Maharashtra"},
  {"Name":"Devu Brahmam Achary","State":"Orissa"},
  {"Name":"Medimi Venkata Krishna","State":"Orissa"},
  {"Name":"Nyayapati Lakshmana Rao","State":"Orissa"},
  {"Name":"M venkateswara Rao","State":"Orissa"},
  {"Name":"V.srinivas","State":"Orissa"},
  {"Name":"Vemuri subhash Naidu","State":"Orissa"},
  {"Name":"G Kailash","State":"Orissa"},
  {"Name":"Kolli Sreenivasa Rao","State":"Orissa"},
  {"Name":"kumar","State":"Orissa"},
  {"Name":"J Mohan Rao","State":"Orissa"},
  {"Name":"K Siva Prasad Subuddhi","State":"Orissa"},
  {"Name":"P Chittibabu","State":"Orissa"},
  {"Name":"V Visweswara Rao","State":"Orissa"},
  {"Name":"M.Sampat Kumar","State":"Tamil Nadu"},
  {"Name":"GVSR Krishna Murty","State":"Tamil Nadu"},
  {"Name":"P.T.Srinath","State":"Bengal"},
  {"Name":"A.Srinivasarao","State":"Bengal"},
  {"Name":"M.Sivalingam","State":"Bengal"},
  {"Name":"P.Sannibabu","State":"Bengal"},
  {"Name":"NSK Rao","State":"Bengal"},
  {"Name":"E Veeraraju","State":"Bengal"},
  {"Name":"Venugopala Rao, President,, AA,IIT","State":"Bengal"},
  {"Name":"Vedula Venkatarao","State":"Bengal"},
  {"Name":"Vedula Sai Srinivas","State":"Bengal"},
  {"Name":"DM Srivivas","State":"Bengal"},
  {"Name":"Suri Pattabhi","State":"Bengal"},
  {"Name":"DB Yerrayya","State":"Bengal"},
  {"Name":"KRVS Meher","State":"Bengal"},
  {"Name":"Maddu Samba Murthy","State":"Bengal"},
  {"Name":"Pramod Kumar","State":"Bengal"},
  {"Name":"Dhavala Visveswararao","State":"Bengal"},
  {"Name":"Rallapalli Padma Prasad","State":"Bengal"},
  {"Name":"Katyayani","State":"Bengal"},
  {"Name":"K.V.Ramana rao","State":"Bengal"},
  {"Name":"Devatha Subramaniyam","State":"Bengal"},
  {"Name":"Kolla Lokeswara Rao","State":"Bengal"},
  {"Name":"Ganti Pradeep","State":"Bengal"},
  {"Name":"Bantupalli Sundara Rao","State":"Bengal"},
  {"Name":"VVL Srinivasa Murty","State":"Delhi"},
  {"Name":"B.Chanti Prasada Rao","State":"Bengal"},
  {"Name":"N/Nagabhushana Rao","State":"Orissa"},
  {"Name":"B.Krishna Rao","State":"Kharagur"},
  {"Name":"P.Bhasakara Rao","State":"Kharagur"},
  {"Name":"PV Appala Das","State":"Kharagur"},
  {"Name":"V Nageswara Rao","State":"Kharagur"},
  {"Name":"Chenna Reddy","State":"Kharagur"},
  {"Name":"M Yagna narayana","State":"kerala"},
  {"Name":"Sappidi","State":"Orissa"},
  {"Name":"Asipu Bairagi","State":"Bengal"},
  {"Name":"P.Bhaskara Reddy","State":"karnataka"},
  {"Name":"Hanumantha Rao","State":"karnataka"},
  {"Name":"M. Ramaswami Reddy","State":"Tamil Nadu"},
  {"Name":"P.Krishna Murty","State":"Orissa"},
  {"Name":"Otti Bhuteswar","State":"Bengal"},
  {"Name":"Korada Nageswar Rao","State":"Bengal"},
  {"Name":"Battala Rama Rao","State":"Bengal"},
  {"Name":"Boda Tarakesu","State":"Bengal"},
  {"Name":"Pilli Mohan Rao","State":"Bengal"},
  {"Name":"Telukula Krishna Shahu","State":"Bengal"},
  {"Name":"Balla Prakash Rao","State":"Bengal"},
  {"Name":"Ankam Syamala","State":"Bengal"},
  {"Name":"Vaka Bharathi","State":"Bengal"},
  {"Name":"Allaka Madhubabu","State":"Bengal"},
  {"Name":"KSR Krishna","State":"Maharashtra"},
  {"Name":"B.SUBBA RAO","State":"Bengal"},
  {"Name":"V. SHIVA SATYANANDAM","State":"Bengal"},
  {"Name":"M. PATTABHIRAM","State":"Bengal"},
  {"Name":"G. ANANDA RAO","State":"Orissa"},
  {"Name":"D. MURALIKRISHNA","State":"Orissa"},
  {"Name":"B. BULLIAH CHOWDARY","State":"Orissa"},
  {"Name":"V. VEERABHADRA RAO","State":"Orissa"},
  {"Name":"P. JAYARAMULU","State":"Orissa"},
  {"Name":"DR. RSN MURTY","State":"Orissa"},
  {"Name":"K S R RAMESH","State":"Orissa"},
  {"Name":"P. VENUGOPAL","State":"Orissa"},
  {"Name":"RUDRA MURTHY","State":"chhattisgarh"},
  {"Name":"ANANDARAO PATNAIK","State":"Orissa"},
  {"Name":"BABURAO MAHANTY","State":"Orissa"},
  {"Name":"L. KALAVATHI","State":"Orissa"},
  {"Name":"S. VISWANADHA RAO","State":"chhattisgarh"},
  {"Name":"A. PADMAVATHI","State":"Delhi"},
  {"Name":"M. KUSUMA","State":"Delhi"},
  {"Name":"Y. PARVATHI REDDY","State":"Delhi"},
  {"Name":"VIJYAKUMAR","State":"Tamil Nadu"},
  {"Name":"A.M. SUBRAHMANYAM","State":"Tamil Nadu"},
  {"Name":"MADHUKUMAR REDDY","State":"Tamil Nadu"},
  {"Name":"M. CHANDRASEKHAR","State":"Tamil Nadu"},
  {"Name":"M.S. LAKSHMA REDDY","State":"Tamil Nadu"},
  {"Name":"D.Koteeswara Rao","State":"Karnataka"},
  {"Name":"Chennappa","State":"Karnataka"},
  {"Name":"Renuka","State":"Maharashtra"},
  {"Name":"K.KEDARINATH","State":"Orissa"},
  {"Name":"SETUPATI ADINARAYANA","State":"Orissa"},
  {"Name":"G SEKHAR REDDY","State":"karnataka"},
  {"Name":"G MUNI REDDY","State":"Tamil Nadu"},
  {"Name":"NANDULA RAMAKRISHNA","State":"Maharashtra"},
  {"Name":"Syamala Devi","State":"Bangalore"},
  {"Name":"Tirumala Kumar","State":"Chennai"},
  {"Name":"R.Sankaran","State":"Chennai"},
  {"Name":"PH Rao","State":"Ahmedabad"},
  {"Name":"Jonnalagadda Srinath","State":"Trivendrum"},
  {"Name":"Srinivasa Murty Mellacheruvu","State":"Ranchi/Vemuru"},
  {"Name":"Erramilli Sri Mata","State":"Ankaleswar"},
  {"Name":"Lellapalli Sridevi Ramesh","State":"Chennai"},
  {"Name":"RVSN Murty","State":"Kharagapur"},
  {"Name":"Chellapilla Vardhan Kumar","State":"Kharagpur"},
  {"Name":"Janatala Jyotsna","State":"Bhuvaneswar"},
  {"Name":"B RajeshWara Raju","State":"kharagpur"},
  {"Name":"Ivaturi Dhana Lakshmi","State":"kharagpur"},
  {"Name":"KV Rao","State":"Silvassa"},
  {"Name":"Venkateswara Rao","State":"Hospeta Karnataka"},
  {"Name":"Prayaga Aruna","State":"Kharagapur"},
  {"Name":"Sudhakara Reddy","State":"Lucknow"},
  {"Name":"KV Rajeswara Rao","State":"Jaipur"},
  {"Name":"K.Srinivas","State":"Guwahati"},
  {"Name":"NN Murty","State":"Nagpur"},
  {"Name":"Sangineni Ravindra","State":"Bombay"},
  {"Name":"C Murali Krishna","State":"Bangalore"},
  {"Name":"N.Krishna Reddy","State":"Hosur"},
  {"Name":"R.Gajendra Murty","State":"Hosur"},
  {"Name":"K.Tyagaraj","State":"Hosur"},
  {"Name":"Sonti Sarada","State":"Bhuvaneswar"},
  {"Name":"SN Srinivas","State":"Bhuvaneswar"},
  {"Name":"AV Sitaramaiah","State":"Hosur"},
  {"Name":"P.Ramalingeswara Rao","State":"Cuttack"},
  {"Name":"M Ramachandrappa","State":"Hosur"},
  {"Name":"A purnalata","State":"Kolcutta"},
  {"Name":"P.Srinivasa Rao","State":"Bilaspur"},
  {"Name":"G Krishnappa","State":"Hosur"},
  {"Name":"Deverakonda Vaidya Narayana Rao","State":"Bhuvaneswar"},
  {"Name":"A Malleswara Rao","State":"Serampre"},
  {"Name":"K Suryanarayana Murty","State":"Chennai"},
  {"Name":"Dr Sivam Arun Kumar","State":"Bilaspur"},
  {"Name":"B Ramakrishna","State":"Jajpur Road"},
  {"Name":"Reddy Veeraswamy","State":"Bilaspur"},
  {"Name":"C.Jagadeeswari","State":"Banguluru"},
  {"Name":"Malyadri","State":"Banguluru"},
  {"Name":"M.Muniraju","State":"Banguluru"},
  {"Name":"DNV Rama Sarma","State":"Banguluru"},
  {"Name":"Darla Venkateswarlu","State":"Banguluru"},
  {"Name":"B Prabhakara Rao","State":"Kharagapur"},
  {"Name":"A. Chandra Sekhar","State":"Chennai"},
  {"Name":"KS Jeeva Ratnam","State":"Banguluru"},

 ];
final List<Map<String, String>> listOfassociatemembers =[
  {"Name":"S.A.Nazeer","State":"Telangana"},
  {"Name":"Dantu Subba Rao","State":"Telangana"},
  {"Name":"M.Anantham","State":"Telangana"},
  {"Name":"Smt. V.Kanaka Durga","State":"Telangana"},
  {"Name":"KBS Sarma","State":"Telangana"},
  {"Name":"Dr. GV Purnachand","State":"Andhra Pradesh"},
  {"Name":"Smt. Prabhala Janaki","State":"Telangana"},
  {"Name":"Dr.Kolli Mohana Rao","State":"Andhra Pradesh"},
  {"Name":"GLN Murty","State":"Telangana"},
  {"Name":"Bandi Lakshmi Narayana","State":"Kakinada"},
  {"Name":"Ananda Mohan Voruganti","State":"Hyderabad"},
  {"Name":"Chaganti Uma","State":"vizag"},
  {"Name":"T Girija","State":"Hyderabad"},
  ];