List<String> updates = [
  'RTS  CELEBRATED ITS 5TH ANNIVERSARY ON 28TH JUNE 2020 ONLINE. SEVERAL VIP’S AND 10  TOP ARTISTS FROM DIFFERENT CULTURAL FIELDS  PARTICIPATED IN THE EVENT.',
  'AS PART OF RTS ANNIVERSARY CELEBRATIONS, INTERNATIONAL KAVI SAMMELANAM ON CORONA WAS ORGANISED ON 5TH JULY 2020 WITH PARTICIPATION FROM 12 COUNTRY POETS IN THE WORLD. 400 POETS GAVE VERSUS ON THREE PARELLEL VIRTUAL STAGES NAMED AFTER THREE GNANPITH AWARDEES VISWANADHA SATYANARAYANA, C. NARAYANA REDDY AND RAVURI BHARADWAJA FOR 7 HOURS EACH. ',
  'TELUGU BOOK OF RECORDS RECOGNISED TWO RECORDS EVENTS OF BIGGEST ONLINE CULTURAL GATHERING ON 28TH JUNE 2020, AND LARGEST TELUGU KAVI SAMMELANAM ON 5TH JULY 2020.',
  'WORLD TELUGU CULTUAL FESTIVAL  2020 LED BY TANA TO COORDINATE WTCF IN RASHTRETARA TELUGU AREAS. RTS LED A 64 MEMBER TEAM FOR SUCCESSFUL ORGANISATION OF WTCF. RTS WORKED IN TANNDEM WTH TELUGU ASSOCIATIONS IN 47 COUNTRIES.',
  'TOTAL OF 18300 PARTICIPANTS TOOK PART IN WTCF. RTS CONTRIBUTED SEVERAL THOUSANDS OF PARTICIPATED, 150 JUDGES AND 50 TECHNICAL COORDINATORS. THUS MAKING PRESENCE OF RTS ON INTERNATIONAL STAGE.',
  'PRESIDENT OF RTS SRI R. SUNDARA RAO CO-CERTIFIES PARTICIPANTS FROM INDIA WITH HIS SIGNATURE.',
];
