List<String> updates = [
  'HON. VICE PRESIDENT OF INDIA SRI M.VENKAIAH NAIDU TELEPHONED SRI PVPC PRASAD, SECRETARY RTS ON 13TH MAY 2020 AND ENQUIRED ABOUT ACTIVITIES OF RTS AND EFFECT OF CARONA ON TELUGU PEOPLE',
  'RTS HAS SENT 21 SENIOR MEMBERS AS JUDGES TO WORLD ENVIRONMENTAL DAY CELEBRATIONS ORGANISED BY TANA FROM 5TH TO 7TH JUN 2020',
  'RTS GUJARAT UNIT IN COORDINATION WITH OTHER TELUGU ASSOCIATIONS COORDINATED WITH GUJARAT GOVERNMENT AND SENT TWO SHRAMIK TRAINS TO TELANGANA AND ANDHRA PRADESH ON 23RD AND 25TH JUN 2020',
  'RTS JOINED HANDS WITH OTHER TELUGU ORGANISATIONS IN PROTESTING AGAINST ATTEMPTS FOR INTRUSION OF TWO TAMIL LETTERS IN TELUGU UNI CODE',
  'RTS KHARAGAPUR MEMBERS  COLLECTED DONATIONS AND  DISTRIBUTED FOOD POCKETS  FOR ONE WEEK TO AFFECTED CARONA PERSONS',
  'PROPOSED RTS SAHITYOTSAVAM IN ASSOCIATION WITH GAJAPATI TELUGU ASSOCIATION IN PARLAKHIMIDI ON 7TH AND 8TH JUN 2020  IS POSTPONED DUE TO COVID CONDITIONS AND  LOCK DOWN',
];
